[package]
name = "imxrt118x-pac"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = { version = "0.7", optional = true }
defmt = { version = "0.3", optional = true }

[features]
rt = ["cortex-m-rt/device"]
defmt = ["dep:defmt"]
